from brownie import (
    network,
    accounts,
    config,
)

FORKED_LOCAL_ENVIRONMENTS = ["mainnet-fork", "mainnet-fork-dev"]
LOCAL_BLOCKCHAIN_ENVIRONMENTS = ["development", "ganache-local", "mainnet-fork"]


def get_account(index=None, account_id=None):
    if index is not None:
        return accounts[index]
    if account_id is not None:
        return accounts.load(id)
    active_network: str = network.show_active()
    if (
        active_network in LOCAL_BLOCKCHAIN_ENVIRONMENTS
        or active_network in FORKED_LOCAL_ENVIRONMENTS
    ):
        # use one of the accounts automatically generated by brownie
        return accounts[0]
    return accounts.add(config["wallets"]["from_key"])
